name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'  # Change to the desired Go version

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build hello.go

    - name: Test
      run: go test ./...

    - name: Run Go program
      run: go run hello.go
